import Ember from 'ember';
import web3 from 'ember-web3/services/web3';
// import set from 'ember-metal/set';
import get from 'ember-metal/get';

export default Ember.Route.extend({

    web3: Ember.inject.service(),
    myContract:{},
    abi:{},
    code:{},
    beforeModel:function() {             
        // var Web3 = require('web3');
        // var web3 = new Web3();
        // web3.setProvider(new web3.providers.HttpProvider("http://localhost:8545"));
         
        // solidity code code
        let source = "" +
        "contract test {\n" +
        "   function multiply(uint a) constant returns(uint d) {\n" +
        "       return a * 7;\n" +
        "   }\n" +
        "}\n";
        let webInstance = this.get('web3.web3Instance');
        console.log(web3);
        // console.log(webInstance);
        // debugger;
        let compiled = webInstance.eth.compile.solidity(source);
        let code =  get(this,'code');
        let abi = get(this,'abi');
        code = compiled["<stdin>:test"].code;
        // contract json abi, this is autogenerated using solc CLI
        abi = compiled["<stdin>:test"].info.abiDefinition; 
        console.log('code : '+code +'   abi : '+ abi);   
    },
	actions:{
        // initContract: 
		createExampleContract:function() {
            let code = get(this,'code');
            let abi = get(this,'abi');
            let myContract = get(this,'myContract');
            // hide create button
            document.getElementById('create').style.visibility = 'hidden'; 
            document.getElementById('code').innerText = code;

            let webInstance = this.get('web3.web3Instance');
            // let's assume that coinbase is our account
            webInstance.eth.defaultAccount = webInstance.eth.coinbase;

            // create contract
            document.getElementById('status').innerText = "transaction sent, waiting for confirmation";
            webInstance.eth.contract(abi).new({data: code}, function (err, contract) {
                if(err) {
                    console.error(err);
                    return;
                // callback fires twice, we only want the second call when the contract is deployed
                } else if(contract.address){

                    myContract = contract;
                    console.log('address: ' + myContract.address);
                    document.getElementById('status').innerText = 'Mined!';
                    document.getElementById('call').style.visibility = 'visible';
                }
            });
		},
		callExampleContract: function() {
			// this should be generated by ethereum
            let param = parseInt(document.getElementById('value').value);
            let myContract = get(this,'myContract');
            
            // call the contract
            let res = myContract.multiply(param);
            document.getElementById('result').innerText = res.toString(10);
        }
	}
});
